server:
  port: 8484
  servlet:
    encoding:
      #SpingBoot内置了CharacterEncodingFilter编码过滤，默认为ISO-8859-1
      enabled: true
      #设置CharacterEncodingFilter编码格式为UTF-8
      charset: utf-8
      force: true
    context-path: /electricity

  ssl:
    key-store: classpath:xian-yun.xyz.jks
    key-store-type: JKS
    key-alias: xian-yun.xyz
    key-store-password: u9q3q576o13l0hc
    key-password: u9q3q576o13l0hc


spring:
  profiles:
    #启用database.yml配置
    active: database

  mvc:
    pathmatch:
      #swagger配置
      matching-strategy: ant_path_matcher

yiqu:
  jwt:
    # 部署上线务必修改此配置，以保证token的安全性
    secret: YIQU!@#$%^&*767299026
    expire: 28800
    header: token

#fdfs文件系统
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  thumb-image:
    height: 150
    width: 150
  tracker-list: 175.178.212.107:22122

#shiro包中redis-jedis连接主机配置
shiro:
  redis:
    redisHost: 172.17.0.3:6379
    password: LSL!20010418
    databaseIndex: 15