spring:
  #druid数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: xyz.lsl.vue.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
