server:
  port: 8484
  servlet:
    encoding:
      #SpingBoot内置了CharacterEncodingFilter编码过滤，默认为ISO-8859-1
      enabled: true
      #设置CharacterEncodingFilter编码格式为UTF-8
      charset: utf-8
      force: true
    context-path: /vue

spring:
  profiles:
    #启用database.yml配置
    active: database

  mvc:
    pathmatch:
      #swagger配置
      matching-strategy: ant_path_matcher

yiqu:
  jwt:
    # 部署上线务必修改此配置，以保证token的安全性
    secret: nihao!@#$%^&*123456
    expire: 28800
    header: token

#fdfs文件系统
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  thumb-image:
    height: 150
    width: 150
  tracker-list:

#shiro包中redis-jedis连接主机配置
shiro:
  redis:
    redisHost:
    password:
    databaseIndex: